name: "Test"
description: "Runs project tests and lints"
inputs:
  ssh_key:
    description: "SSH key to inject into docker build"
    required: false
  python_version:
    description: "The python version to use"
    required: true
    default: "3.12"
  jfrog_pypi_user:
    description: "jfrog user"
    required: false
  jfrog_pypi_token:
    description: "jfrog token"
    required: false

runs:
  using: "composite"
  steps:
    - if: inputs.ssh_key != ''
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ inputs.python_version }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: "x64"

    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        port: 8000
        cors: "*"

    - name: Start Redis
      shell: bash
      run: |
        docker rm -f redis >/dev/null 2>&1 || true
        docker run --name redis --detach --publish 6379:6379 redis/redis-stack-server:latest
        for i in {1..30}; do
          if [[ "$(docker exec redis redis-cli ping)" == "PONG" ]]; then
            exit 0
          fi
          sleep 1
        done
        docker logs redis
        echo "Redis did not become ready in time"
        exit 1

    - name: Start MongoDB
      shell: bash
      run: |
        docker rm -f mongodb >/dev/null 2>&1 || true
        docker run --name mongodb --detach --publish 27017:27017 \
          -e MONGO_INITDB_ROOT_USERNAME=root \
          -e MONGO_INITDB_ROOT_PASSWORD=root \
          -e MONGO_INITDB_DATABASE=alby \
          mongo:7.0.5
        for i in {1..45}; do
          if [[ "$(docker exec mongodb mongosh --quiet --username root --password root --authenticationDatabase admin --eval "db.adminCommand({ ping: 1 }).ok")" == "1" ]]; then
            exit 0
          fi
          sleep 1
        done
        docker logs mongodb
        echo "MongoDB did not become ready in time"
        exit 1

    - name: Start RabbitMQ
      uses: namoshek/rabbitmq-github-action@v1
      with:
        ports: "5672:5672 15672:15672"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Sync dependencies
      env:
        UV_INDEX_BLUECORE_USERNAME: ${{ inputs.jfrog_pypi_user }}
        UV_INDEX_BLUECORE_PASSWORD: ${{ inputs.jfrog_pypi_token }}
      run: cd src && uv sync
      shell: bash

    - name: Run tests
      run: |
        cd src && DYNAMO_ENDPOINT_URL=http://localhost:8000 uv --offline run pytest ./tests
      env:
        AWS_ACCESS_KEY_ID: "random"
        AWS_SECRET_ACCESS_KEY: "random"
        AWS_DEFAULT_REGION: "us-west-2"
      shell: bash

    - name: Check formatting (black)
      run: |
        cd src && uv --offline run black . --check
      shell: bash
