name: "Deploy GraphQL subgraph to AWS Lambda"
description: "Deploys GQL Subgraph Lambda"
inputs:
  service_name:
    description: "service name"
    required: true
  service_stage:
    description: "service stage"
    required: true    
  aws_region:
    description: "AWS region"
    required: false
    default: "us-west-2"
  aws_access_key_id: "AWS Access Key ID"
    required: true
  aws_secret_access_key: "AWS Secret Access Key"
    required: true
  min_instances:
    description: "Minimum number of instances to launch"
    default: 1
  max_instances:
    description: "Maximum number of instances to launch"
    default: 100
  timeout:
    description: "Timeout rules for service"
    default: 30
  memory:
    description: "RAM size in Mb (e.g. 512, 1024, 2048)"
    default: "512Mi"
  cpu:
    description: "Number of vCPU core"
    default: 1
  tags:
    description: 'AWS Labels, Formatted like: environment=staging,service=my_service,etc..'
    required: false
    default: ""
  apollo_graph_ref:
    description: 'apollo graph ref'
    required: true
  apollo_key:
    description: 'apollo API key'
    required: true
  gql_routing_url:
    description: 'routing URL for apollo'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm ci

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage ${{ inputs.service_stage }} --region ${{ inputs.aws_region }}
      env:
        SERVICE_NAME: ${{ inputs.service_name }}        
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}        

    - name: Get apollo args
      id: apollo_args
      run: |-
        echo "GQL_ROUTING_URL=${{ inputs.gql_routing_url }}" >> ${GITHUB_ENV}
        echo "APOLLO_KEY=${{ inputs.apollo_key }}" >> ${GITHUB_ENV}        
      shell: bash

    - name: Install Rover
      run: |-
        curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
        # Add Rover to the $GITHUB_PATH so it can be used in another step
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
        echo "$HOME/.rover/bin" >> $GITHUB_PATH
      shell: bash

    - name: Publish Schema to Studio using rover
      run: |-
        rover subgraph introspect ${{ inputs.apollo_routing_url }} | rover subgraph publish ${{ inputs.apollo_graph_ref }} --name ${{ inputs.service_name }} --schema - --routing-url ${{ inputs.apollo_routing_url }}
      shell: bash
