name: "Deploy Serverless AWS ECS"
description: "Deploys Terraform ECS"
inputs:
  service_name:
    description: "service name"
    required: true
  service_stage:
    description: "service stage"
    required: true
  aws_region:
    description: "AWS region"
    required: false
    default: "us-west-2"
  aws_role_to_assume_env:
    description: "AWS IAM role in deployment env to assume"
    required: true
  timeout:
    description: "Timeout rules for service"
    default: 30

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume_env }}
        aws-region: ${{ inputs.aws_region }}

    #####################################################
    ############## Run ECR Upload Steps #################
    #####################################################
    # Login to AWS ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Set the timestamp
    - name: Get the current date for the image tag
      id: date
      run: echo "::set-output name=IMAGE_TAG::$(date +'%Y%m%d%H%M%S')"
      shell: bash

    # Build, Tag, and Push the Docker image
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.service_name }}
        IMAGE_TAG: ${{ steps.date.outputs.IMAGE_TAG }}
        SERVICE_NAME: ${{ inputs.service_name }}
      run: |
        pwd
        ls -al
        docker buildx build --platform=linux/amd64 -f ./src/Dockerfile -t "$SERVICE_NAME" ./src/
        docker tag "$SERVICE_NAME" "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      shell: bash

    - name: Pass Docker image tag to the environment
      env:
        IMAGE_TAG: ${{ steps.date.outputs.IMAGE_TAG }}
      run: | 
        echo "DOCKER_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "::set-output name=dock_img_tag::DOCKER_IMAGE_TAG"
      shell: bash