name: "Plan ECS deployment"
description: "Plan ECS deployment"
inputs:
  service_name:
    description: "service name"
    required: true
  service_stage:
    description: "service stage"
    required: true
  aws_region:
    description: "AWS region"
    required: false
    default: "us-west-2"
  aws_role_to_assume_env:
    description: "AWS IAM role in deployment env to assume"
    required: true
  timeout:
    description: "Timeout rules for service"
    default: 30
  apollo_graph_ref:
    description: "Apollo graph ref"
    required: true
  apollo_key:
    description: "Apollo API key"
    required: true
  apollo_routing_url:
    description: "Apollo routing URL"
    required: true
  service_env_vars:
    description: "env vars passed into EKS"
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume_env }}
        aws-region: ${{ inputs.aws_region }}

    #####################################################
    ############## Run ECR Upload Steps #################
    #####################################################
    # Set the timestamp
    - name: Get the current date for the image tag
      id: date
      run: echo "::set-output name=IMAGE_TAG::$(date +'%Y%m%d%H%M%S')"
      shell: bash

    - name: Pass Docker image tag to the environment
      env:
        IMAGE_TAG: ${{ steps.date.outputs.IMAGE_TAG }}
      run: echo "DOCKER_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash

    #####################################################
    ############## Run Terraform Steps ##################
    #####################################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    - name: ECS deploy via Terraform
      run: | 
        echo "DOCKER_IMAGE_TAG ${{ env.DOCKER_IMAGE_TAG }}"
        cd terraform/deployment
        terraform init -backend-config=${{ inputs.service_stage }}/${{ inputs.service_stage }}_${{ inputs.aws_region }}_backend_config.tfvars 
        terraform plan -var-file=${{ inputs.service_stage }}/${{ inputs.service_stage }}_${{ inputs.aws_region }}.tfvars \
                                      -var "service_env_vars=${{ inputs.service_env_vars }}" \
                                      -var "docker_image_tag=${{ env.DOCKER_IMAGE_TAG }}"
      shell: bash